sglc_admin:
  resource: "@ServerGroveLiveChatBundle/Controller/AdminController.php"
  type:     annotation
  prefix:   /admin

sglc_admin_2:
  resource: "@ServerGroveLiveChatBundle/Controller/Admin/"
  type:     annotation
  prefix:   /admin

sglc_chat:
  resource: "@ServerGroveLiveChatBundle/Controller/ChatController.php"
  type:     annotation

sglc_tracker:
  resource: "@ServerGroveLiveChatBundle/Controller/TrackController.php"
  type:     annotation
  prefix:   /tracker

sglc_default:
  resource: "@ServerGroveLiveChatBundle/Controller/DefaultController.php"
  type:     annotation