imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    secret:        %secret%
    charset:       UTF-8
    csrf_protection:
        enabled: true
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        lifetime:       0
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
#doctrine:
#    dbal:
#        driver:   %database_driver%
#        host:     %database_host%
#        dbname:   %database_name%
#        user:     %database_user%
#        password: %database_password%
#        logging:  %kernel.debug%

doctrine_mongodb:
  connections:
    default:
      server: mongodb://localhost:27017
      options:
        connect: true
  default_database: livechat
  auto_generate_hydrator_classes: true
  auto_generate_proxy_classes: true
  document_managers:
    default:
      mappings:
        SGLiveChatBundle: ~
      metadata_cache_driver: array # array, apc, xcache, memcache
 
#    orm:
#        auto_generate_proxy_classes: %kernel.debug%
#        mappings:
#            AcmeDemoBundle: ~

# Swiftmailer Configuration
swiftmailer: ~
#    transport:  %mailer_transport%
#    host:       %mailer_host%
#    username:   %mailer_user%
#    password:   %mailer_password%

sg_live_chat:
  cache_engine: mongo