# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

sglivechat:
  resource: "@ServerGroveLiveChatBundle/Resources/config/routing.yml"