security:
    encoders:
        ServerGrove\LiveChatBundle\Document\Operator: sha512
        ServerGrove\LiveChatBundle\Document\Administrator: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_OPERATOR:    ROLE_USER
        ROLE_ADMIN:       ROLE_OPERATOR
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            id: server_grove_live_chat.user.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                default_target_path: /sglivechat/admin
                login_path:          /sglivechat/admin/login
                check_path:          /sglivechat/admin/login-check
                username_parameter: login[email]
                password_parameter: login[passwd]
            logout:
                path:   /sglivechat/admin/logout
                target: /sglivechat/admin/login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/sglivechat/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sglivechat/admin/[\w\/\-]+/new, roles: ROLE_ADMIN }
        - { path: ^/sglivechat/admin/[\w\/\-]+/create, roles: ROLE_ADMIN }
        - { path: ^/sglivechat/admin/[\w\/\-]+/edit, roles: ROLE_ADMIN }
        - { path: ^/sglivechat/admin/[\w\/\-]+/update, roles: ROLE_ADMIN }
        - { path: ^/sglivechat/admin/[\w\/\-]+/delete, roles: ROLE_ADMIN }
        - { path: ^/sglivechat/admin, roles: ROLE_USER }