sglc_admin:
  resource: "@SGLiveChatBundle/Controller/AdminController.php"
  type:     annotation


homepage:
  pattern:  /
  defaults: { _controller: SGLiveChatBundle:Default:index }

# -- Live Chat -----------------------------------------------------------------

sglc_chat_homepage:
    pattern:  /sglivechat
    defaults: { _controller: SGLiveChatBundle:Chat:index }

sglc_chat_invite:
  pattern: /sglivechat/{sessId}/invite
  defaults: { _controller: SGLiveChatBundle:Chat:invite }

sglc_chat_invite_accept:
  pattern: /sglivechat/{id}/invite/accept
  defaults: { _controller: SGLiveChatBundle:Chat:acceptInvite }

sglc_chat_invite_reject:
  pattern: /sglivechat/{id}/invite/reject
  defaults: { _controller: SGLiveChatBundle:Chat:rejectInvite }

sglc_chat_load:
  pattern: /sglivechat/{id}/load
  defaults: { _controller: SGLiveChatBundle:Chat:load }

sglc_chat_accept:
  pattern: /sglivechat/{id}/accept
  defaults: { _controller: SGLiveChatBundle:Chat:accept }

sglc_chat_reject:
  pattern: /sglivechat/{id}/reject/
  defaults: { _controller: SGLiveChatBundle:Chat:reject }
  
sglc_chat_user_action:
  pattern: /sglivechat/{id}/user/action/{action}
  defaults: { _controller: SGLiveChatBundle:Chat:userAction }

sglc_chat_done:
  pattern: /sglivechat/{id}/done
  defaults: { _controller: SGLiveChatBundle:Chat:done }

sglc_chat_send:
  pattern: /sglivechat/{id}/send
  defaults: { _controller: SGLiveChatBundle:Chat:send }
  requirements: { _method: post }

sglc_chat_messages:
  pattern: /sglivechat/{id}/messages.{_format}
  defaults: { _controller: SGLiveChatBundle:Chat:messages, _format: html }
  requirements: { _method: get }
  
sglc_chat_status:
  pattern: /sglivechat/status
  defaults: { _controller: SGLiveChatBundle:Chat:status }
  requirements: { _method: get }


# -- Tracker -------------------------------------------------------------------

sglc_track_index:
  pattern: /js/sglivechat-tracker
  defaults: { _controller: SGLiveChatBundle:Track:index }
  requirements: { _method: get }

sglc_track_updater:
  pattern: /js/sglivechat-tracker/update
  defaults: { _controller: SGLiveChatBundle:Track:update }

sglc_track_reset:
  pattern: /js/sglivechat-tracker/reset
  defaults: { _controller: SGLiveChatBundle:Track:reset }
sglc_track_status:
  pattern: /js/sglivechat-tracker/status.{_format}
  defaults: { _controller: SGLiveChatBundle:Track:status, _format: html }